#!/bin/sh
#
# jc - shorthand to call java compiler
# with appropriate CLASSPATH and arguments

cd ../../../..
CLASSPATH=`pwd`/classes:`pwd`/javasrc:"$CLASSPATH"
export CLASSPATH

for f
do
  set -x
  javac -d classes javasrc/iicm/vrml/pwutils/$f
done
